### ISSUE TITLE
Resources Not Found Exception

### ISSUE THREAD

**Issue by StephaneBg** [negusoft/holoaccent#14] opened 2014-02-01 10:35 UTC
I get an exception when using the library.
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ha__list_selector_transition.xml from drawable resource ID #0x7f020069

You can easily reproduce the problem with this project:
https://github.com/StephaneBg/HoloAccentTest

**Comment by blurkidi** [comment] 2014-02-01 15:21
I  checked the code and everything seemed fine. Then I cloned your repo and it runs perfectly, no crashes at all.
You can try to do a "Sync Project with Gradle Files" and clean the project, just in case. Otherwise, you can post the full stack trace and I can have a better look at it.

**Comment by StephaneBg** [comment] 2014-02-01 15:26
The app doesn't crash but you can see the error in the logcat when launching.
When you open the project with Android Studio and you see your layout in the design view, you have several error messages.

**Comment by MariusVolkhart** [comment] 2014-02-01 22:58
I see something similar in my logcats. It doesn't cause an application crash, and the display actually works fine, but I do see the warning. @StephaneBg is this the same/similar issue?

``` java
02-01 16:54:59.362      872-885/? W/WindowManager﹕ Token{431312b8 ActivityRecord{420771c8 u0 com.volkhart.ecn.debug/com.volkhart.ecn.MainActivity t1533}} failed creating starting window
    android.view.InflateException: Binary XML file line #30: Error inflating class <unknown>
            at android.view.LayoutInflater.createView(LayoutInflater.java:620)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
            at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:2966)
            at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3029)
            at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1678)
            at com.android.internal.policy.impl.PhoneWindowManager.addStartingWindow(PhoneWindowManager.java:1701)
            at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:7202)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:137)
            at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
            at android.view.LayoutInflater.createView(LayoutInflater.java:594)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
            at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:2966)
            at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3029)
            at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1678)
            at com.android.internal.policy.impl.PhoneWindowManager.addStartingWindow(PhoneWindowManager.java:1701)
            at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:7202)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:137)
            at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ha__actionbar_background.xml from drawable resource ID #0x7f02000c
            at android.content.res.Resources.loadDrawable(Resources.java:2099)
            at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
            at android.view.View.<init>(View.java:3563)
            at android.view.ViewGroup.<init>(ViewGroup.java:470)
            at android.widget.FrameLayout.<init>(FrameLayout.java:101)
            at android.widget.FrameLayout.<init>(FrameLayout.java:97)
            at com.android.internal.widget.ActionBarContainer.<init>(ActionBarContainer.java:52)
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
            at android.view.LayoutInflater.createView(LayoutInflater.java:594)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
            at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:2966)
            at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3029)
            at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1678)
            at com.android.internal.policy.impl.PhoneWindowManager.addStartingWindow(PhoneWindowManager.java:1701)
            at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:7202)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:137)
            at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: android.content.res.Resources$NotFoundException: File  from drawable resource ID #0x7f020102
            at android.content.res.Resources.loadDrawable(Resources.java:2119)
            at android.content.res.Resources.getDrawable(Resources.java:700)
            at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:159)
            at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:937)
            at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
            at android.content.res.Resources.loadDrawable(Resources.java:2095)
            at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
            at android.view.View.<init>(View.java:3563)
            at android.view.ViewGroup.<init>(ViewGroup.java:470)
            at android.widget.FrameLayout.<init>(FrameLayout.java:101)
            at android.widget.FrameLayout.<init>(FrameLayout.java:97)
            at com.android.internal.widget.ActionBarContainer.<init>(ActionBarContainer.java:52)
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
            at android.view.LayoutInflater.createView(LayoutInflater.java:594)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
            at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:2966)
            at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3029)
            at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1678)
            at com.android.internal.policy.impl.PhoneWindowManager.addStartingWindow(PhoneWindowManager.java:1701)
            at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:7202)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:137)
            at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.io.FileNotFoundException:
            at android.content.res.AssetManager.openNonAssetNative(Native Method)
            at android.content.res.AssetManager.openNonAsset(AssetManager.java:408)
            at android.content.res.Resources.loadDrawable(Resources.java:2110)
            at android.content.res.Resources.getDrawable(Resources.java:700)
            at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:159)
            at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:937)
            at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
            at android.content.res.Resources.loadDrawable(Resources.java:2095)
            at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
            at android.view.View.<init>(View.java:3563)
            at android.view.ViewGroup.<init>(ViewGroup.java:470)
            at android.widget.FrameLayout.<init>(FrameLayout.java:101)
            at android.widget.FrameLayout.<init>(FrameLayout.java:97)
            at com.android.internal.widget.ActionBarContainer.<init>(ActionBarContainer.java:52)
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
            at android.view.LayoutInflater.createView(LayoutInflater.java:594)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
            at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:2966)
            at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3029)
            at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1678)
            at com.android.internal.policy.impl.PhoneWindowManager.addStartingWindow(PhoneWindowManager.java:1701)
            at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:7202)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:137)
            at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by StephaneBg** [comment] 2014-02-02 10:53
Yes it is the same issue I observe in my logcat. I confirm that it breaks the design preview in Android Studio. See attached screenshot.
![design_view](https://f.cloud.github.com/assets/1014339/2060079/2ec424b6-8bf8-11e3-8c64-e208a3dd69aa.PNG)

**Comment by blurkidi** [comment] 2014-02-03 10:28
Well, that exception doesn't break the design view, they are two separate issues. The preview will not work because the library does some "tricks" at runtime. I recommend using the native Holo theme for the design view and check the final result by running the app. It will basically be the same with the accent color changed.

About the exception in the warning. It seems that the app tries to load some drawables (related to the actionbar) before the activity itself. The call doesn't pass through AccentResources so it fails to get certain drawables. I can fix this by giving these "dummie drawables" a default value. The warning is harmless because the drawables will be loaded correctly afterwards but it will be fixed in future releases.

**Comment by StephaneBg** [comment] 2014-02-03 17:12
Sorry for my English. By "break" I meant there is an error message.
Thanks for the explanations about the root cause.

**Comment by blurkidi** [comment] 2014-02-04 20:37
No problem, I understood what you meant. And I just wanted to point out that there are two separate issues, so the explanations are different too.
Thanks you very much for reporting the issue.

**Comment by Megatron1000** [comment] 2014-02-11 14:21
Think I'm seeing the same thing in my app. Getting a lot of Crashes showing up in Crashlytics with the heading: 

Fatal Exception: android.view.InflateException
android.view.View.<init>

I haven't seen a crash happen myself though.

Here's a stack trace:
android.view.InflateException: Binary XML file line #27: Error inflating class <unknown>
       at android.view.LayoutInflater.createView(LayoutInflater.java:613)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
       at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:2812)
       at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:2875)
       at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1568)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2797)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2235)
       at android.app.ActivityThread.access$600(ActivityThread.java:141)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5048)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:675)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
       at android.view.LayoutInflater.createView(LayoutInflater.java:587)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
       at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:2812)
       at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:2875)
       at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1568)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2797)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2235)
       at android.app.ActivityThread.access$600(ActivityThread.java:141)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5048)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:675)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ha__actionbar_background.xml from drawable resource ID #0x7f020024
       at android.content.res.Resources.loadDrawable(Resources.java:1953)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
       at android.view.View.<init>(View.java:3330)
       at android.view.ViewGroup.<init>(ViewGroup.java:431)
       at android.widget.FrameLayout.<init>(FrameLayout.java:101)
       at android.widget.FrameLayout.<init>(FrameLayout.java:97)
       at com.android.internal.widget.ActionBarContainer.<init>(ActionBarContainer.java:52)
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
       at android.view.LayoutInflater.createView(LayoutInflater.java:587)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
       at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:2812)
       at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:2875)
       at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1568)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2797)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2235)
       at android.app.ActivityThread.access$600(ActivityThread.java:141)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5048)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:675)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: android.content.res.Resources$NotFoundException: File  from drawable resource ID #0x7f020121
       at android.content.res.Resources.loadDrawable(Resources.java:1970)
       at android.content.res.Resources.getDrawable(Resources.java:660)
       at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:156)
       at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:885)
       at android.graphics.drawable.Drawable.createFromXml(Drawable.java:822)
       at android.content.res.Resources.loadDrawable(Resources.java:1950)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
       at android.view.View.<init>(View.java:3330)
       at android.view.ViewGroup.<init>(ViewGroup.java:431)
       at android.widget.FrameLayout.<init>(FrameLayout.java:101)
       at android.widget.FrameLayout.<init>(FrameLayout.java:97)
       at com.android.internal.widget.ActionBarContainer.<init>(ActionBarContainer.java:52)
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
       at android.view.LayoutInflater.createView(LayoutInflater.java:587)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
       at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:2812)
       at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:2875)
       at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1568)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2797)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2235)
       at android.app.ActivityThread.access$600(ActivityThread.java:141)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5048)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:675)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.io.FileNotFoundException
       at android.content.res.AssetManager.openNonAssetNative(AssetManager.java)
       at android.content.res.AssetManager.openNonAsset(AssetManager.java:407)
       at android.content.res.Resources.loadDrawable(Resources.java:1962)
       at android.content.res.Resources.getDrawable(Resources.java:660)
       at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:156)
       at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:885)
       at android.graphics.drawable.Drawable.createFromXml(Drawable.java:822)
       at android.content.res.Resources.loadDrawable(Resources.java:1950)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
       at android.view.View.<init>(View.java:3330)
       at android.view.ViewGroup.<init>(ViewGroup.java:431)
       at android.widget.FrameLayout.<init>(FrameLayout.java:101)
       at android.widget.FrameLayout.<init>(FrameLayout.java:97)
       at com.android.internal.widget.ActionBarContainer.<init>(ActionBarContainer.java:52)
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
       at android.view.LayoutInflater.createView(LayoutInflater.java:587)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
       at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:2812)
       at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:2875)
       at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1568)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2797)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2235)
       at android.app.ActivityThread.access$600(ActivityThread.java:141)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5048)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:675)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by blurkidi** [comment] 2014-02-12 08:49
It seems like the same exception, are you sure that it makes the app crash? Doesn't Crashlytics indicate whether it is a warning or an actual crash? Other info like the device and the android version would be useful too.

**Comment by Megatron1000** [comment] 2014-02-12 09:25
I've not seen it crash myself, so I'm not sure if it is bailing out or not. It's showing as a fatal exception in Crashlytics, which I assume is a crash. I'm only able to test on KitKat but it seems to happen on 4.0 to 4.2 from the reports. Here's are links to some of the reports, if that helps.

http://crashes.to/s/9b5d8a4e93d
http://crashes.to/s/de50ebb4a89

**Comment by blurkidi** [comment] 2014-02-17 10:44
Suddenly, I can't reproduce the exception that is shown as a warning. I am trying the app on the Nexus 4, where I could perfectly see the warning, and also on a Galaxy Nexus with Android 4.3.

Could you confirm that you still get the Exception? The only change I can think of is that I update Android Studio. In fact, I would be really glad if this bug was due to gradle.

**Comment by blurkidi** [comment] 2014-02-26 13:35
I guess that I coulnd't see the exception because I had a filter on.... anyway, the but is now fixed on the dev branch. If anybody feels like testing, I would appreciate some feedback. I will close the issue in a couple of days.

**Comment by Megatron1000** [comment] 2014-03-03 20:18
I'll give it a shot. Can you tell me how I add the dev branch into my Gradle dependency though?

**Comment by blurkidi** [comment] 2014-03-04 09:06
I had quite hard time adding the dependency. But it is something like this:

1- Get a copy of the repo under your project directory, I did it in a folder called "submodules"
git clone https://github.com/negusoft/holoaccent.git
git checkout dev

2- Add the project to the gradle build:
In the root settings.gradle file add 'include 'submodules:holoaccent:HoloAccent' and in the your projects build.gradle file add the followinig under dependencies: compile project(':submodules:holoaccent:HoloAccent')

3- Now the tricky part. It seems that there is a bug in the android gradle plugin so we need to remove the android version and group properties from the subproject.
In the "submodules/holoaccent/build.gradle" file remove the two lines that indicate the version and the group under allprojects. 

You will have to remove the maven dependency that you already had before, but the project is set now.

**Comment by Megatron1000** [comment] 2014-03-13 13:42
Thanks for the instructions. I've tried it but I keep getting this error in the Gradle sync
'Configuration with name 'default' not found.'
I'm not too sure what it means. Any idea how to fix it? Might just be worth making the dev branch live as it's been a while now.

**Comment by blurkidi** [comment] 2014-03-13 14:44
I don't know about the error, it looks like a pretty generic one. You can maybe google it:
http://stackoverflow.com/questions/17188489/android-studio-gradle-configuration-with-name-default-not-found

**Closed as completed** 2014-03-18 08:00 UTC
