### ISSUE TITLE
StackOverflowError in AccentResources.checkInitialized()

### ISSUE THREAD

**Issue by riley-van-hengstum** [negusoft/holoaccent#33] opened 2014-07-21 07:18 UTC
I got the following exception on at least three different devices:

```
Caused by: java.lang.StackOverflowError
at com.negusoft.holoaccent.AccentResources.checkInitialized(AccentResources.java:148)
at com.negusoft.holoaccent.AccentResources.getColor(AccentResources.java:214)
at android.content.res.TypedArray.getThemeColor(TypedArray.java:751)
at android.content.res.TypedArray.getColor(TypedArray.java:319)
at com.negusoft.holoaccent.AccentResources.initPalette(AccentResources.java:179)
at com.negusoft.holoaccent.AccentResources.initialize(AccentResources.java:154)

at com.negusoft.holoaccent.AccentResources.checkInitialized(AccentResources.java:148)
...
```

**Comment by blurkidi** [comment] 2014-07-23 07:30
I am trying to reproduce this to be able to fix it. Could you give me some clues in what situation it happens? (and on what situations it doesn't?)

Does it happen with the sample app? Is it with an app of yours? could you share some snippets? How do you define your theme? Do you override the accent color in code? What devices? ...

**Comment by riley-van-hengstum** [comment] 2014-07-23 09:13
The crashes appear in the Google Play Developer Console. Unfortunately, I can't reproduce them myself.

It is my own application, relevant files are in this gist:
https://gist.github.com/Jaap-van-Hengstum/9afef694207ae3f9fbf5

I don't override the accent color in the code.

Devices are:
- HUAWEI P6 (hwp6-u06)  (Android 4.2)
- hwG525-U00 (Android 4.1)
- G700-U10 (hwG700-U10)
- P7-L10 (hwp7)

So it appears they are all Huawei devices, perhaps Huawei does something funky in the thememanager.

Let me know if you need more info.

## 

ps. thanks for your work on this library. I submitted your library to the [AndroidWeekly](http://androidweekly.net/issues/issue-105) newsletter a few weeks ago, I hope it generated some additional downloads for your library. It seems we won't need it anymore for Android L, which is imho a good thing.

**Comment by riley-van-hengstum** [comment] 2014-07-23 11:17
I checked the _android.content.res.TypedArray_ class and the _getColor()_ method from the stock Android code and it does not seem to contain / call the _getThemeColor()_ method. I guess this is something Huawei added.

**Comment by blurkidi** [comment] 2014-07-23 11:59
I think I can fix the issue by adding a bit of defensive code, but without being able to test it I can't really guarantee that it will be fixed. I will let you know when it is ready if you want to play around.

**Comment by blurkidi** [comment] 2014-07-23 13:28
I created a branch called issue_33 that should fix the problem. I didn't upload it to maven so you will have to set up the project with HoloAccent as a gradle module, you can have a look at the sample app as a reference.

Or you can upload it to your own maven repository if you prefer.

If somebody could reproduce the bug and then confirm that this fix works, that would be perfect.

**Comment by fehbari** [comment] 2014-07-29 16:45
I'm having the same issue with Huawei devices in my app. I've received Crashlytics reports on this and will add some information here. Hopefully it helps.

Devices:

![captura de tela 2014-07-29 13 33 48](https://cloud.githubusercontent.com/assets/3378355/3738216/621adf86-173e-11e4-8458-69985e72d032.png)

Stack trace:

``` java
java.lang.StackOverflowError
       at com.negusoft.holoaccent.AccentResources.initialize()
       at com.negusoft.holoaccent.AccentResources.checkInitialized()
       at com.negusoft.holoaccent.AccentResources.getColor()
       at android.content.res.TypedArray.getThemeColor(TypedArray.java:751)
       at android.content.res.TypedArray.getColor(TypedArray.java:319)
       at com.negusoft.holoaccent.AccentResources.checkInitialized()
       at com.negusoft.holoaccent.AccentResources.initialize()
       at com.negusoft.holoaccent.AccentResources.checkInitialized()
       at com.negusoft.holoaccent.AccentResources.getColor()
       ...
```

I'll try your attempted fix on branch issue_33. If I no longer receive crash reports we can assume it worked.

It would be great if you could later upload the fix to Maven though.

**Comment by blurkidi** [comment] 2014-07-29 17:02
That would be great, thanks. But still, the best way to confirm that the issue is fixed would be to try it in an actual Huawei device. But indeed, if you don't get a crash in a while, it will mean that the bug is fixed.

And yes, I will release a new version and push it to maven central when it is fixed.

**Comment by pinhao** [comment] 2014-08-29 09:26
I was having this issue on a Huawei MediaPad 10 Link+ so I tested branch issue_33 and it solved the problem.

**Comment by blurkidi** [comment] 2014-09-03 01:20
Great news! Thanks. I will merge the branch and create a new release soon (probably next week, after my hollidays :)

**Comment by blurkidi** [comment] 2014-09-10 18:55
Done, v1.0.1 is released and available in maven central. It includes the fix for this issue. And I finally got my hands on a Huawei so I confirm that the issue is fixed.

Thanks to everybody for the help.

**Closed as completed** 2014-09-10 18:56 UTC
